apiVersion: metal.afritzler.github.io/v1alpha1
kind: BareMetalHost
metadata:
  name: compute-5
spec:
  systemId: "System-5"
  power: "Off"
  bootMACAddress: "da:ef:6f:1d:82:3e"
  bmc:
    address: http://127.0.0.1:8000
    type: RedfishLocal
    secretRef:
      name: foo
