apiVersion: metal.afritzler.github.io/v1alpha1
kind: BareMetalHost
metadata:
  name: compute-1
spec:
  systemId: "System-1"
  power: "Off"
  bootMACAddress: "bc:55:85:92:de:b7"
  bmc:
    address: http://127.0.0.1:8000
    type: RedfishLocal
    secretRef:
      name: foo
