# permissions for end users to edit baremetalhostclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: baremetalhostclaim-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: baremetal-operator
    app.kubernetes.io/part-of: baremetal-operator
    app.kubernetes.io/managed-by: kustomize
  name: baremetalhostclaim-editor-role
rules:
- apiGroups:
  - core.afritzler.github.io.afritzler.github.io
  resources:
  - baremetalhostclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.afritzler.github.io.afritzler.github.io
  resources:
  - baremetalhostclaims/status
  verbs:
  - get
