apiVersion: metal.afritzler.github.io/v1alpha1
kind: BareMetalHost
metadata:
  name: baremetalhost-sample
spec:
  systemId: "System-1"
  power: "On"
  fooUuid: "122334234234"
  bootMACAddress: "bc:55:85:92:de:b7"
  bmc:
    address: http://127.0.0.1:8000
    type: Redfish
    secretRef:
      name: foo
      namespace: default
